# Generated by Django 4.2.4 on 2023-09-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="imgae_name",
            new_name="imga_name",
        ),
    ]
