# Generated by Django 4.2.4 on 2023-09-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_imgae_name_post_imga_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="imga_name",
            new_name="image_name",
        ),
    ]
