# Generated by Django 4.2.4 on 2023-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_imga_name_post_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.ImageField(upload_to="posts"),
        ),
    ]
